services:
  postgres:
    image: postgres:16
    container_name: neobank-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: neobank
      POSTGRES_USER: neobank
      POSTGRES_PASSWORD: neobank
      TZ: UTC
      PGTZ: UTC
