services:

  postgres:
    image: postgres:16
    container_name: neobank-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: neobank
      POSTGRES_USER: neobank
      POSTGRES_PASSWORD: neobank
      TZ: UTC
    volumes:
      - neobank_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U neobank" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: neobank-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  neobank_pgdata:
